import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./_components/providers/NextAuthProvider";
import "@tldraw/tldraw/tldraw.css";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner";
import ReactQueryClientProvider from "./_components/providers/ReactQueryClientProvider";
export const metadata: Metadata = {
  title: "Saas App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <ReactQueryClientProvider>
          <body className={inter.className}>
            {children}
            <Toaster richColors className="!z-[33333]" />
          </body>
        </ReactQueryClientProvider>
      </NextAuthProvider>
    </html>
  );
}
